### ISSUE TITLE
Is there a paper on this work that we can cite?

### ISSUE THREAD

**Issue by basket163** [trunk96/wireless-network-simulator-v2#1]

**Comment by trunk96** [comment]
Hi,
thank you for the interest on my work!
At the moment I have a decision pending paper that fully describes the
simulator, but in the meantime you can cite:

Calvanese Strinati, E, Barbarossa, S, Choi, T, et al. 6G in the sky:
On-demand intelligence at the edge of 3D networks (Invited paper). ETRI
Journal. 2020; 42: 643– 657. https://doi.org/10.4218/etrij.2020-0205

where a preliminary version of the simulator has been employed.

I will take care of updating the DOI once the decision pending paper will
be published.

Thank you again,
Emanuele De Santis

Il gio 20 mag 2021, 13:54 basketguo ***@***.***> ha scritto:

**Comment by basket163** [comment]
Thank you very much. Your work and paper are very helpful to us.
